# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/local/muttand11213/untitled folder/battaglia_navale-main"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/local/muttand11213/untitled folder/battaglia_navale-main"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/local/muttand11213/untitled folder/battaglia_navale-main/CMakeFiles" "/home/local/muttand11213/untitled folder/battaglia_navale-main/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/local/muttand11213/untitled folder/battaglia_navale-main/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named replay

# Build rule for target.
replay: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 replay
.PHONY : replay

# fast build rule for target.
replay/fast:
	$(MAKE) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/build
.PHONY : replay/fast

#=============================================================================
# Target rules for targets named battaglia_navale

# Build rule for target.
battaglia_navale: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 battaglia_navale
.PHONY : battaglia_navale

# fast build rule for target.
battaglia_navale/fast:
	$(MAKE) -f CMakeFiles/battaglia_navale.dir/build.make CMakeFiles/battaglia_navale.dir/build
.PHONY : battaglia_navale/fast

#=============================================================================
# Target rules for targets named Battleship

# Build rule for target.
Battleship: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Battleship
.PHONY : Battleship

# fast build rule for target.
Battleship/fast:
	$(MAKE) -f CMakeFiles/Battleship.dir/build.make CMakeFiles/Battleship.dir/build
.PHONY : Battleship/fast

src/AttackGrid.o: src/AttackGrid.cpp.o

.PHONY : src/AttackGrid.o

# target to build an object file
src/AttackGrid.cpp.o:
	$(MAKE) -f CMakeFiles/Battleship.dir/build.make CMakeFiles/Battleship.dir/src/AttackGrid.cpp.o
.PHONY : src/AttackGrid.cpp.o

src/AttackGrid.i: src/AttackGrid.cpp.i

.PHONY : src/AttackGrid.i

# target to preprocess a source file
src/AttackGrid.cpp.i:
	$(MAKE) -f CMakeFiles/Battleship.dir/build.make CMakeFiles/Battleship.dir/src/AttackGrid.cpp.i
.PHONY : src/AttackGrid.cpp.i

src/AttackGrid.s: src/AttackGrid.cpp.s

.PHONY : src/AttackGrid.s

# target to generate assembly for a file
src/AttackGrid.cpp.s:
	$(MAKE) -f CMakeFiles/Battleship.dir/build.make CMakeFiles/Battleship.dir/src/AttackGrid.cpp.s
.PHONY : src/AttackGrid.cpp.s

src/Battleship.o: src/Battleship.cpp.o

.PHONY : src/Battleship.o

# target to build an object file
src/Battleship.cpp.o:
	$(MAKE) -f CMakeFiles/Battleship.dir/build.make CMakeFiles/Battleship.dir/src/Battleship.cpp.o
.PHONY : src/Battleship.cpp.o

src/Battleship.i: src/Battleship.cpp.i

.PHONY : src/Battleship.i

# target to preprocess a source file
src/Battleship.cpp.i:
	$(MAKE) -f CMakeFiles/Battleship.dir/build.make CMakeFiles/Battleship.dir/src/Battleship.cpp.i
.PHONY : src/Battleship.cpp.i

src/Battleship.s: src/Battleship.cpp.s

.PHONY : src/Battleship.s

# target to generate assembly for a file
src/Battleship.cpp.s:
	$(MAKE) -f CMakeFiles/Battleship.dir/build.make CMakeFiles/Battleship.dir/src/Battleship.cpp.s
.PHONY : src/Battleship.cpp.s

src/Coord.o: src/Coord.cpp.o

.PHONY : src/Coord.o

# target to build an object file
src/Coord.cpp.o:
	$(MAKE) -f CMakeFiles/Battleship.dir/build.make CMakeFiles/Battleship.dir/src/Coord.cpp.o
.PHONY : src/Coord.cpp.o

src/Coord.i: src/Coord.cpp.i

.PHONY : src/Coord.i

# target to preprocess a source file
src/Coord.cpp.i:
	$(MAKE) -f CMakeFiles/Battleship.dir/build.make CMakeFiles/Battleship.dir/src/Coord.cpp.i
.PHONY : src/Coord.cpp.i

src/Coord.s: src/Coord.cpp.s

.PHONY : src/Coord.s

# target to generate assembly for a file
src/Coord.cpp.s:
	$(MAKE) -f CMakeFiles/Battleship.dir/build.make CMakeFiles/Battleship.dir/src/Coord.cpp.s
.PHONY : src/Coord.cpp.s

src/DefenceGrid.o: src/DefenceGrid.cpp.o

.PHONY : src/DefenceGrid.o

# target to build an object file
src/DefenceGrid.cpp.o:
	$(MAKE) -f CMakeFiles/Battleship.dir/build.make CMakeFiles/Battleship.dir/src/DefenceGrid.cpp.o
.PHONY : src/DefenceGrid.cpp.o

src/DefenceGrid.i: src/DefenceGrid.cpp.i

.PHONY : src/DefenceGrid.i

# target to preprocess a source file
src/DefenceGrid.cpp.i:
	$(MAKE) -f CMakeFiles/Battleship.dir/build.make CMakeFiles/Battleship.dir/src/DefenceGrid.cpp.i
.PHONY : src/DefenceGrid.cpp.i

src/DefenceGrid.s: src/DefenceGrid.cpp.s

.PHONY : src/DefenceGrid.s

# target to generate assembly for a file
src/DefenceGrid.cpp.s:
	$(MAKE) -f CMakeFiles/Battleship.dir/build.make CMakeFiles/Battleship.dir/src/DefenceGrid.cpp.s
.PHONY : src/DefenceGrid.cpp.s

src/ExplorationSubmarine.o: src/ExplorationSubmarine.cpp.o

.PHONY : src/ExplorationSubmarine.o

# target to build an object file
src/ExplorationSubmarine.cpp.o:
	$(MAKE) -f CMakeFiles/Battleship.dir/build.make CMakeFiles/Battleship.dir/src/ExplorationSubmarine.cpp.o
.PHONY : src/ExplorationSubmarine.cpp.o

src/ExplorationSubmarine.i: src/ExplorationSubmarine.cpp.i

.PHONY : src/ExplorationSubmarine.i

# target to preprocess a source file
src/ExplorationSubmarine.cpp.i:
	$(MAKE) -f CMakeFiles/Battleship.dir/build.make CMakeFiles/Battleship.dir/src/ExplorationSubmarine.cpp.i
.PHONY : src/ExplorationSubmarine.cpp.i

src/ExplorationSubmarine.s: src/ExplorationSubmarine.cpp.s

.PHONY : src/ExplorationSubmarine.s

# target to generate assembly for a file
src/ExplorationSubmarine.cpp.s:
	$(MAKE) -f CMakeFiles/Battleship.dir/build.make CMakeFiles/Battleship.dir/src/ExplorationSubmarine.cpp.s
.PHONY : src/ExplorationSubmarine.cpp.s

src/Game.o: src/Game.cpp.o

.PHONY : src/Game.o

# target to build an object file
src/Game.cpp.o:
	$(MAKE) -f CMakeFiles/Battleship.dir/build.make CMakeFiles/Battleship.dir/src/Game.cpp.o
.PHONY : src/Game.cpp.o

src/Game.i: src/Game.cpp.i

.PHONY : src/Game.i

# target to preprocess a source file
src/Game.cpp.i:
	$(MAKE) -f CMakeFiles/Battleship.dir/build.make CMakeFiles/Battleship.dir/src/Game.cpp.i
.PHONY : src/Game.cpp.i

src/Game.s: src/Game.cpp.s

.PHONY : src/Game.s

# target to generate assembly for a file
src/Game.cpp.s:
	$(MAKE) -f CMakeFiles/Battleship.dir/build.make CMakeFiles/Battleship.dir/src/Game.cpp.s
.PHONY : src/Game.cpp.s

src/GamePc.o: src/GamePc.cpp.o

.PHONY : src/GamePc.o

# target to build an object file
src/GamePc.cpp.o:
	$(MAKE) -f CMakeFiles/Battleship.dir/build.make CMakeFiles/Battleship.dir/src/GamePc.cpp.o
.PHONY : src/GamePc.cpp.o

src/GamePc.i: src/GamePc.cpp.i

.PHONY : src/GamePc.i

# target to preprocess a source file
src/GamePc.cpp.i:
	$(MAKE) -f CMakeFiles/Battleship.dir/build.make CMakeFiles/Battleship.dir/src/GamePc.cpp.i
.PHONY : src/GamePc.cpp.i

src/GamePc.s: src/GamePc.cpp.s

.PHONY : src/GamePc.s

# target to generate assembly for a file
src/GamePc.cpp.s:
	$(MAKE) -f CMakeFiles/Battleship.dir/build.make CMakeFiles/Battleship.dir/src/GamePc.cpp.s
.PHONY : src/GamePc.cpp.s

src/GamePlayer.o: src/GamePlayer.cpp.o

.PHONY : src/GamePlayer.o

# target to build an object file
src/GamePlayer.cpp.o:
	$(MAKE) -f CMakeFiles/Battleship.dir/build.make CMakeFiles/Battleship.dir/src/GamePlayer.cpp.o
.PHONY : src/GamePlayer.cpp.o

src/GamePlayer.i: src/GamePlayer.cpp.i

.PHONY : src/GamePlayer.i

# target to preprocess a source file
src/GamePlayer.cpp.i:
	$(MAKE) -f CMakeFiles/Battleship.dir/build.make CMakeFiles/Battleship.dir/src/GamePlayer.cpp.i
.PHONY : src/GamePlayer.cpp.i

src/GamePlayer.s: src/GamePlayer.cpp.s

.PHONY : src/GamePlayer.s

# target to generate assembly for a file
src/GamePlayer.cpp.s:
	$(MAKE) -f CMakeFiles/Battleship.dir/build.make CMakeFiles/Battleship.dir/src/GamePlayer.cpp.s
.PHONY : src/GamePlayer.cpp.s

src/Grid.o: src/Grid.cpp.o

.PHONY : src/Grid.o

# target to build an object file
src/Grid.cpp.o:
	$(MAKE) -f CMakeFiles/Battleship.dir/build.make CMakeFiles/Battleship.dir/src/Grid.cpp.o
.PHONY : src/Grid.cpp.o

src/Grid.i: src/Grid.cpp.i

.PHONY : src/Grid.i

# target to preprocess a source file
src/Grid.cpp.i:
	$(MAKE) -f CMakeFiles/Battleship.dir/build.make CMakeFiles/Battleship.dir/src/Grid.cpp.i
.PHONY : src/Grid.cpp.i

src/Grid.s: src/Grid.cpp.s

.PHONY : src/Grid.s

# target to generate assembly for a file
src/Grid.cpp.s:
	$(MAKE) -f CMakeFiles/Battleship.dir/build.make CMakeFiles/Battleship.dir/src/Grid.cpp.s
.PHONY : src/Grid.cpp.s

src/HelpShip.o: src/HelpShip.cpp.o

.PHONY : src/HelpShip.o

# target to build an object file
src/HelpShip.cpp.o:
	$(MAKE) -f CMakeFiles/Battleship.dir/build.make CMakeFiles/Battleship.dir/src/HelpShip.cpp.o
.PHONY : src/HelpShip.cpp.o

src/HelpShip.i: src/HelpShip.cpp.i

.PHONY : src/HelpShip.i

# target to preprocess a source file
src/HelpShip.cpp.i:
	$(MAKE) -f CMakeFiles/Battleship.dir/build.make CMakeFiles/Battleship.dir/src/HelpShip.cpp.i
.PHONY : src/HelpShip.cpp.i

src/HelpShip.s: src/HelpShip.cpp.s

.PHONY : src/HelpShip.s

# target to generate assembly for a file
src/HelpShip.cpp.s:
	$(MAKE) -f CMakeFiles/Battleship.dir/build.make CMakeFiles/Battleship.dir/src/HelpShip.cpp.s
.PHONY : src/HelpShip.cpp.s

src/Replay.o: src/Replay.cpp.o

.PHONY : src/Replay.o

# target to build an object file
src/Replay.cpp.o:
	$(MAKE) -f CMakeFiles/Battleship.dir/build.make CMakeFiles/Battleship.dir/src/Replay.cpp.o
.PHONY : src/Replay.cpp.o

src/Replay.i: src/Replay.cpp.i

.PHONY : src/Replay.i

# target to preprocess a source file
src/Replay.cpp.i:
	$(MAKE) -f CMakeFiles/Battleship.dir/build.make CMakeFiles/Battleship.dir/src/Replay.cpp.i
.PHONY : src/Replay.cpp.i

src/Replay.s: src/Replay.cpp.s

.PHONY : src/Replay.s

# target to generate assembly for a file
src/Replay.cpp.s:
	$(MAKE) -f CMakeFiles/Battleship.dir/build.make CMakeFiles/Battleship.dir/src/Replay.cpp.s
.PHONY : src/Replay.cpp.s

src/Ship.o: src/Ship.cpp.o

.PHONY : src/Ship.o

# target to build an object file
src/Ship.cpp.o:
	$(MAKE) -f CMakeFiles/Battleship.dir/build.make CMakeFiles/Battleship.dir/src/Ship.cpp.o
.PHONY : src/Ship.cpp.o

src/Ship.i: src/Ship.cpp.i

.PHONY : src/Ship.i

# target to preprocess a source file
src/Ship.cpp.i:
	$(MAKE) -f CMakeFiles/Battleship.dir/build.make CMakeFiles/Battleship.dir/src/Ship.cpp.i
.PHONY : src/Ship.cpp.i

src/Ship.s: src/Ship.cpp.s

.PHONY : src/Ship.s

# target to generate assembly for a file
src/Ship.cpp.s:
	$(MAKE) -f CMakeFiles/Battleship.dir/build.make CMakeFiles/Battleship.dir/src/Ship.cpp.s
.PHONY : src/Ship.cpp.s

src/main-replay.o: src/main-replay.cpp.o

.PHONY : src/main-replay.o

# target to build an object file
src/main-replay.cpp.o:
	$(MAKE) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/main-replay.cpp.o
.PHONY : src/main-replay.cpp.o

src/main-replay.i: src/main-replay.cpp.i

.PHONY : src/main-replay.i

# target to preprocess a source file
src/main-replay.cpp.i:
	$(MAKE) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/main-replay.cpp.i
.PHONY : src/main-replay.cpp.i

src/main-replay.s: src/main-replay.cpp.s

.PHONY : src/main-replay.s

# target to generate assembly for a file
src/main-replay.cpp.s:
	$(MAKE) -f CMakeFiles/replay.dir/build.make CMakeFiles/replay.dir/src/main-replay.cpp.s
.PHONY : src/main-replay.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/battaglia_navale.dir/build.make CMakeFiles/battaglia_navale.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/battaglia_navale.dir/build.make CMakeFiles/battaglia_navale.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/battaglia_navale.dir/build.make CMakeFiles/battaglia_navale.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... replay"
	@echo "... battaglia_navale"
	@echo "... edit_cache"
	@echo "... Battleship"
	@echo "... src/AttackGrid.o"
	@echo "... src/AttackGrid.i"
	@echo "... src/AttackGrid.s"
	@echo "... src/Battleship.o"
	@echo "... src/Battleship.i"
	@echo "... src/Battleship.s"
	@echo "... src/Coord.o"
	@echo "... src/Coord.i"
	@echo "... src/Coord.s"
	@echo "... src/DefenceGrid.o"
	@echo "... src/DefenceGrid.i"
	@echo "... src/DefenceGrid.s"
	@echo "... src/ExplorationSubmarine.o"
	@echo "... src/ExplorationSubmarine.i"
	@echo "... src/ExplorationSubmarine.s"
	@echo "... src/Game.o"
	@echo "... src/Game.i"
	@echo "... src/Game.s"
	@echo "... src/GamePc.o"
	@echo "... src/GamePc.i"
	@echo "... src/GamePc.s"
	@echo "... src/GamePlayer.o"
	@echo "... src/GamePlayer.i"
	@echo "... src/GamePlayer.s"
	@echo "... src/Grid.o"
	@echo "... src/Grid.i"
	@echo "... src/Grid.s"
	@echo "... src/HelpShip.o"
	@echo "... src/HelpShip.i"
	@echo "... src/HelpShip.s"
	@echo "... src/Replay.o"
	@echo "... src/Replay.i"
	@echo "... src/Replay.s"
	@echo "... src/Ship.o"
	@echo "... src/Ship.i"
	@echo "... src/Ship.s"
	@echo "... src/main-replay.o"
	@echo "... src/main-replay.i"
	@echo "... src/main-replay.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

